### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by delaynore** [delaynore/exchange-currencies#3]
- [x] Глобальный обработчик исключений
- [x] Сделать отправку ошибок пользователю при получении результата с сервиса
- [x] Добавить это [link](https://github.com/zhukovsd/java-backend-learning-course/blob/main/Projects/CurrencyExchange/index.md#%D0%BE%D0%B1%D0%BC%D0%B5%D0%BD-%D0%B2%D0%B0%D0%BB%D1%8E%D1%82%D1%8B)

**Comment by delaynore** [comment]
- [x] Добавить swagger
- [x] Добавить mapper
- [ ] Написать тесты
- [ ] Разбить на проекты (архитектура)

**Comment by delaynore** [comment]
- [ ] Сделать документацию для swagger

**Comment by delaynore** [comment]
- [ ] Что-то сделать с ошибками возвращаемыми пользователю

**Comment by delaynore** [comment]
- [x] Добавить асинхронность
